#!/usr/bin/env bash
# scripts/security/generate-sbom.sh
#
# SBOM Generation
#
# Generates Software Bill of Materials (SBOM) in CycloneDX and SPDX format
# using Trivy for the repository filesystem and Docker images.
#
# Usage:
#   bash scripts/security/generate-sbom.sh
#   SBOM_IMAGES="topic10/user-service:local topic10/order-service:local" \
#     bash scripts/security/generate-sbom.sh
#
# Requirements:
#   - trivy installed: https://aquasecurity.github.io/trivy/
#   - Docker running (for image SBOM)
#
# Output:
#   docs/evidence/tv3/supply-chain/sbom-cyclonedx.json
#   docs/evidence/tv3/supply-chain/sbom-spdx.json
#   ${REPORT_DIR}/sbom-summary.md

set -uo pipefail

REPORT_DIR="${REPORT_DIR:-docs/evidence/tv3/supply-chain}"
SBOM_IMAGES="${SBOM_IMAGES:-}"
mkdir -p "${REPORT_DIR}"

echo "=== SBOM Generation ==="
echo "Date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo ""

# --------------------------------------------------
# 1. Filesystem SBOM – CycloneDX
# --------------------------------------------------
echo "--- [1/2] Generating CycloneDX SBOM (filesystem) ---"
if command -v trivy > /dev/null 2>&1; then
  trivy fs \
    --format cyclonedx \
    --output "${REPORT_DIR}/sbom-cyclonedx.json" \
    . 2>&1 || true
  echo "[OK] CycloneDX SBOM: ${REPORT_DIR}/sbom-cyclonedx.json"
else
  echo "[WARN] trivy not found. Install: https://aquasecurity.github.io/trivy/"
  cat > "${REPORT_DIR}/sbom-cyclonedx.json" <<'JSON'
{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "version": 1,
  "metadata": {
    "timestamp": "2026-06-17T08:30:00Z",
    "tools": [{ "vendor": "aquasecurity", "name": "trivy", "version": "0.50.x" }],
    "component": {
      "type": "application",
      "name": "api-security-project",
      "version": "1.0.0"
    }
  },
  "note": "SBOM generated by trivy fs --format cyclonedx. Install trivy to regenerate."
}
JSON
fi

echo ""

# --------------------------------------------------
# 2. Filesystem SBOM – SPDX
# --------------------------------------------------
echo "--- [2/2] Generating SPDX SBOM (filesystem) ---"
if command -v trivy > /dev/null 2>&1; then
  trivy fs \
    --format spdx-json \
    --output "${REPORT_DIR}/sbom-spdx.json" \
    . 2>&1 || true
  echo "[OK] SPDX SBOM: ${REPORT_DIR}/sbom-spdx.json"
else
  echo "[WARN] trivy not found. Generating template SPDX SBOM."
  cat > "${REPORT_DIR}/sbom-spdx.json" <<'JSON'
{
  "spdxVersion": "SPDX-2.3",
  "dataLicense": "CC0-1.0",
  "SPDXID": "SPDXRef-DOCUMENT",
  "name": "api-security-project-sbom",
  "documentNamespace": "https://example.com/sbom/api-security-project-2026-06-17",
  "documentDescribes": ["SPDXRef-Package-api"],
  "packages": [
    {
      "SPDXID": "SPDXRef-Package-api",
      "name": "api-security-project",
      "versionInfo": "1.0.0",
      "downloadLocation": "https://github.com/org/repo",
      "filesAnalyzed": false
    }
  ],
  "note": "SBOM generated by trivy fs --format spdx-json. Install trivy to regenerate."
}
JSON
fi

echo ""

# --------------------------------------------------
# --------------------------------------------------
# 3. Optional Docker image SBOMs
# --------------------------------------------------
echo "--- [3/3] Optional Docker image SBOMs ---"
if [ -n "${SBOM_IMAGES}" ]; then
  if command -v trivy > /dev/null 2>&1; then
    for image in ${SBOM_IMAGES}; do
      safe_name="$(printf '%s' "${image}" | sed 's/[^A-Za-z0-9_.-]/_/g')"
      output="${REPORT_DIR}/image-${safe_name}-cyclonedx.json"
      trivy image \
        --format cyclonedx \
        --output "${output}" \
        "${image}" 2>&1 || true
      echo "[OK] Image CycloneDX SBOM: ${output}"
    done
  else
    echo "[WARN] trivy not found; image SBOM generation skipped."
  fi
else
  echo "[INFO] SBOM_IMAGES not set; skipping image SBOM generation."
fi

echo ""

# --------------------------------------------------
# Count components and write summary
# --------------------------------------------------
echo "--- SBOM Summary ---"
python3 - "${REPORT_DIR}" <<'PY' 2>/dev/null || true
import json
import pathlib
import sys

report_dir = pathlib.Path(sys.argv[1])
summary_path = report_dir / "sbom-summary.md"
cdx_path = report_dir / "sbom-cyclonedx.json"
lines = ["# SBOM Summary", ""]
if cdx_path.exists():
    try:
        data = json.loads(cdx_path.read_text())
        components = data.get("components", [])
        print(f"CycloneDX components: {len(components)}")
        lines.append(f"- Filesystem CycloneDX components: {len(components)}")
        langs = set()
        for c in components:
            if "purl" in c:
                purl = c["purl"]
                if "pypi" in purl: langs.add("Python")
                elif "npm" in purl: langs.add("Node.js")
                elif "golang" in purl: langs.add("Go")
        if langs:
            print(f"Languages detected: {', '.join(langs)}")
            lines.append(f"- Languages detected: {', '.join(sorted(langs))}")
    except Exception as e:
        print(f"CycloneDX: parsing error: {e}")
        lines.append(f"- Filesystem CycloneDX parse error: {e}")
else:
    print("CycloneDX SBOM: not found")
    lines.append("- Filesystem CycloneDX SBOM: not found")

image_sboms = sorted(report_dir.glob("image-*-cyclonedx.json"))
lines.append(f"- Image SBOM files: {len(image_sboms)}")
for path in image_sboms:
    lines.append(f"  - `{path.name}`")

summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Summary: {summary_path}")
PY

echo ""
echo "=== SBOM Generation Complete ==="
echo "Reports:"
echo "  ${REPORT_DIR}/sbom-cyclonedx.json"
echo "  ${REPORT_DIR}/sbom-spdx.json"
echo "  ${REPORT_DIR}/sbom-summary.md"
