#!/usr/bin/env bash
# Generate final Git/source evidence from a real Git repository.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" \
  || {
    echo "[ERROR] This script must run inside a real Git repository." >&2
    exit 1
  }

cd "${REPO_ROOT}"

EVIDENCE_DIR="docs/evidence/final"
mkdir -p "${EVIDENCE_DIR}"

HEAD_COMMIT="$(git rev-parse HEAD)"
BRANCH_NAME="$(git branch --show-current)"
GENERATED_AT="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

{
  echo "generated_at=${GENERATED_AT}"
  echo "head_commit=${HEAD_COMMIT}"
  echo "branch=${BRANCH_NAME}"
} > "${EVIDENCE_DIR}/final-main-commit.txt"

{
  echo "generated_at=${GENERATED_AT}"
  echo "repo_root=${REPO_ROOT}"
  echo "branch=${BRANCH_NAME}"
  echo "head_commit=${HEAD_COMMIT}"
  echo "git_user_name=$(git config user.name || true)"
  echo "git_user_email=$(git config user.email || true)"
  echo "git_remote_origin=$(git remote get-url origin 2>/dev/null || true)"
} > "${EVIDENCE_DIR}/final-git-identity.txt"

{
  echo "generated_at=${GENERATED_AT}"
  git status -sb
} > "${EVIDENCE_DIR}/final-git-status.txt"

{
  echo "generated_at=${GENERATED_AT}"
  git log --oneline --decorate -n 20
} > "${EVIDENCE_DIR}/final-recent-commits.txt"

{
  echo "generated_at=${GENERATED_AT}"
  find . -maxdepth 4 \
    -path ./.git -prune -o \
    -path ./node_modules -prune -o \
    -path ./.venv -prune -o \
    -print | sort
} > "${EVIDENCE_DIR}/final-file-tree-maxdepth4.txt"

{
  echo "# Final Quality Gate Summary"
  echo ""
  echo "**Generated:** ${GENERATED_AT}"
  echo "**Branch:** \`${BRANCH_NAME}\`"
  echo "**HEAD:** \`${HEAD_COMMIT}\`"
  echo "**Quality gate status:** Not asserted by this script."
  echo ""
  echo "## Required Reproducible Checks"
  echo ""
  echo "Run these before packaging:"
  echo ""
  echo '```bash'
  echo "bash tests/security/verify-no-tracked-secrets.sh"
  echo "bash ci/run-local-security-scan.sh"
  echo "bash tests/security/network-egress-control-tests.sh"
  echo "bash tests/restler/run-restler-check.sh"
  echo "bash tests/metrics/measure-mttd-mttr.sh"
  echo "bash tests/final/main-regression.sh"
  echo "bash scripts/generate-final-evidence.sh"
  echo '```'
  echo ""
  echo "This file records Git/source evidence and the required command list only. It does not claim that all quality gates passed. Test pass/fail evidence remains in the per-tool output files generated by the commands above."
  echo ""
  echo "## Packaging Rule"
  echo ""
  echo "Generate these files before removing \`.git\` or creating a zip/package archive."
} > "${EVIDENCE_DIR}/final-quality-gate-summary.txt"

echo "Final evidence written to ${EVIDENCE_DIR}"
